#!/bin/bash

# put this in a $PATH directory
# simply sleeps for the given minutes and play a sound when it finishes
# TODO: add notification?!

sleep $(($1 * 60))
paplay /usr/share/sounds/freedesktop/stereo/complete.oga
